name: bencineragofast
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.3
  intl: ^0.15.7

  google_maps: ">=3.0.0 <4.0.0"
  google_maps_flutter: ^0.0.3
  device_id: ^0.1.3

  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.1.0

  rxdart: ^0.20.0
  path_provider: ^0.4.1
  path: ^1.6.2
  uuid: 1.0.3
  english_words: ^3.1.0

  protobuf: ^0.13.4
  protoc_plugin: ^16.0.1
  grpc: ^1.0.1

  location: 1.4.1
  geocoder: 0.1.2

  url_launcher: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true

  assets:
  - assets/images/icono_gas.png
  - assets/images/translade.png
  - assets/images/icono_shell.png
  - assets/images/toyota.png
  - assets/images/ayuda1.png
  - assets/images/ayuda2.png
  - assets/images/ayuda3.png

