name: bencineragofast
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps: ">=3.0.0 <4.0.0"
  google_maps_flutter: ^0.0.3

  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.1.0
  rxdart: ^0.20.0
  sqflite: ^0.13.0+1
  path_provider: ^0.4.1
  path: ^1.6.2

  location: 1.4.1
  geocoder: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter






flutter:


  uses-material-design: true

